# Generated by Django 3.1.7 on 2021-03-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraQu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_qu', models.TextField(choices=[('1', 'Multiple options'), ('2', 'Descriptive '), ('3', 'Data')], default='2', max_length=1)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.extraqu')),
            ],
        ),
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField(default=None)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleOptionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150)),
                ('multiple_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pre_registration.multipleoptions')),
            ],
        ),
        migrations.CreateModel(
            name='MainForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mobile_phone', models.CharField(max_length=11, unique=True)),
                ('home_number', models.CharField(max_length=10, unique=True)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile-pics')),
                ('father_name', models.CharField(max_length=150)),
                ('father_phone_number', models.CharField(max_length=11, unique=True)),
                ('pre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.preregistration')),
            ],
        ),
        migrations.AddField(
            model_name='extraqu',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.preregistration'),
        ),
        migrations.CreateModel(
            name='ExtraAnsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=250)),
                ('extra_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pre_registration.extraans')),
                ('qus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.extraqu')),
            ],
        ),
        migrations.AddField(
            model_name='extraans',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.mainform'),
        ),
    ]
