# Generated by Django 3.1.7 on 2021-03-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_qu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_context', models.CharField(max_length=250)),
                ('qustion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.extra_qu')),
            ],
        ),
    ]
